import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
source rebuilt under markdown2card/src
*/`;

const mode = process.argv[2] || "development";
const prod = mode === "production";
const localBuild = mode === "local";
const paidEntitlementApiUrl = process.env.PAID_ENTITLEMENT_API_URL
  || (localBuild || !prod
    ? "http://127.0.0.1:54321/functions/v1/validate-entitlement"
    : "https://api.markdown2card.invalid/functions/v1/validate-entitlement");

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  define: {
    PAID_ENTITLEMENT_API_URL: JSON.stringify(paidEntitlementApiUrl)
  },
  bundle: true,
  loader: { ".jpg": "dataurl", ".jpeg": "dataurl", ".png": "dataurl" },
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js"
});

if (prod || localBuild) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
